name: cvi
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - numpy
  - matplotlib
  - jupyterlab
  - scipy
  - scikit-learn
  - seaborn
  - flake8
  - ffmpeg
  - black
  - pandas
  - pip
  - pip:
      # - pip install "git+https://git@github.com/shagunsodhani/ml-logger.git@master#egg=ml_logger[all]"
      - hydra-core
