train_cycles: 100
collect_steps: 200
max_value_iters: 100
max_train_samples: 50_000
batch_size: 5
num_batches: 40
device: cuda
eval_steps: 1_000
grid_resolution: 20
vi_tol: 1e-4  # convergence tolerance mean abs grid error
seed: 980237
resample_value_batch: false


augment:
  rollouts: false
  HER: true
  IER: true
  multiplier: 10  # ignored for HER
  rollout_horizon: 10
  random_goal_prob: 0.1  # for rollouts

env:
  _target_: envs.ContinuousGridMDP
  threshold: 0.1
  goal: [0.0, 0.0]
  start: [1.0, 0.0]
  random_start: True
  random_goal: True
  time_limit: 30
  state_dim: 2
  action_dim: 2

agent:
  beta: 0.99  # value cooling factor
  gamma: 0.95  # time discount
  num_action_samples: 100  # to evaluate the best action
  max_delta: 0.1  # for displacement
  epsilon: 0.1  # exploration rate for epsilon greedy
  state_dim: ${env.state_dim}
  action_dim: ${env.action_dim}
  value_network: false  # otherwise knn
  device: ${device}

  transition: 
    _target_: models.Transition
    hidden_dim: 16
    state_dim: ${env.state_dim}
    action_dim: ${env.action_dim}

  optimizer:
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 1e-6
    betas: [0.9, 0.99]
    eps: 1e-4

  state_value:
    _target_: sklearn.neighbors.KNeighborsRegressor
    n_neighbors: 5
    # weights: uniform
    weights: distance

  value_neural_network:
    _target_: models.Value
    hidden_dim: 16
    input_dim: 4

  value_optimizer:
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 1e-6
    betas: [0.9, 0.99]
    eps: 1e-4


  action_value:
    _target_: sklearn.neighbors.KNeighborsRegressor
    n_neighbors: 5
    # weights: uniform
    weights: distance

buffer:
  _target_: buffers.ReplayBufferWithGoals
  size: 100_000

hydra:
  job_logging:
    formatters:
      simple:
        format: '%(asctime)s : %(message)s'
        datefmt: '%H:%M:%S'
  sweep:
    subdir: ${hydra.job.override_dirname}
